# lightning.pytorch==2.0.1.post0
model:
  init_args:
    encoder:
      class_path: twitter.models.TransformerEncoder
      init_args:
        name: "vinai/bertweet-large"
        pooling: "mean"
        gradient_checkpointing: true
    lr: {"encoder": 1.0e-05, "head": 3.0e-04}
    weight_decay: 0.01
