# lightning.pytorch==2.0.1.post0
model:
  init_args:
    encoder:
      class_path: twitter.models.TransformerEncoder
      init_args:
        name: "sentence-transformers/bert-large-nli-mean-tokens"
    lr: {"encoder": 3e-5, "head": 3e-4}
    weight_decay: 0.01
    pooling: "mean"
    freeze_cfg: {1: [1, 2], 2: [3, 4], 3: [5, 6], 4: [7, 8], 5: [9, 10]}

