# lightning.pytorch==2.0.1.post0
model:
  init_args:
    encoder:
      class_path: twitter.models.TransformerEncoder
      init_args:
        name: "cardiffnlp/twitter-roberta-base-sentiment-latest"
        pooling: "cls"
    lr: {"encoder": 3e-5, "head": 3e-4}
    weight_decay: 0.01
